#!/usr/bin/env bash
# remote copy a file

if [ $# -ne 4 ]
	then
		echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
		exit
fi

file=$1
ip=$2
username=$3
key=$4

scp -o StrictHostKeyChecking=no -i "$key" "$file" "$username@$ip:~/"
