#!/usr/bin/env bash
# remote copy a file

if [ $# -eq 4 ]
	then
		file=$1
		ip=$2
		username=$3
		key=$4
		scp -i "$key" "$file" "$username@$ip:~/"
else
		echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
