#!/usr/bin/env bash
# install Nginx
sudo apt-get -y update
sudo apt-get -y install Nginx
echo -e "<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Holberton School the title</title>
  </head>
  <body>
    <header>
    </header>
    <article>
		<h1>Holberton School: Holberton School harder</h1>
		<p>Holberton School paragraph</p>
    </article>
  </body>
</html>" | sudo tee /var/www/html/index.nginx-debian.html 1> /dev/null
sudo service nginx restart
