#!/usr/bin/env bash
# install Nginx
sudo apt-get update
sudo apt-get -y install Nginx
sudo ufw allow 'Nginx HTTP'
sudo rm /var/www/html/index.nginx-debian.html
echo "Holberton School" > index.html
sudo mv index.html /var/www/html
