#!/usr/bin/env bash
# install Nginx
sudo apt-get update
sudo apt-get -y install Nginx
sudo ufw allow 'Nginx HTTP'
echo -e "<!doctype html>
<html lang="en">
	<head>
	</head>
	<body>
		<p>Holberton School</p>
	</body>
</html>" | sudo tee /var/www/html/index.nginx-debian.html 1> /dev/null
sudo service nginx restart
