#!/usr/bin/env bash
# install Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo rm /var/www/html/index.nginx-debian.html
echo"Holberton School" | sudo tee index.html 1> /dev/null
sudo mv index.html /var/www/html
sudo mkdir /var/www/html/redirect_me
echo "No see this" | sudo tee /var/www/html/redirect_me/index.html 1> /dev/null

redirect="\\n\t\tlocation ~ ^/redirect_me/(.*) {\n\t\t\treturn 301 /$1;\n\t\t}"
file="/etc/nginxsites-available/default"
line_num="$(grep -n "}" $file | head -1 | cut -f 1 | tr -d :)"
new_num=$(( line_num + 1 ))
sudo sed "$new_num i $redirect" "$file" | sudo tee new
sudo mv new "$file"
