#!/usr/bin/env bash
# shellcheck disable=SC2154,SC2016
# install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\">
    <title>Holberton School the title</title>
  </head>
  <body>
    <header>
    </header>
    <article>
		<h1>Holberton School: Holberton School harder</h1>
		<p>Holberton School paragraph</p>
    </article>
  </body>
</html>" | sudo tee /var/www/html/index.nginx-debian.html 1> /dev/null
file="/etc/nginx/sites-available/default"
sed -e '/server_name _;/a \\tadd_header X-Served-By $hostname;' $file | sudo tee $file
sudo service nginx restart