#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
user='root'
passwd="$1"
day="$(date +'%d-%m-%Y')"
mysqldump -uroot -p"$1" --all-databases > backup.sql
gzip -c backup.sql > "$day.tar.gz"
