#!/usr/bin/env bash
# FizzBuzz

i=1

while [ $i -le 100 ]; do

	div15=$(( i % 15 ))
	div5=$(( i % 5 ))
	div3=$(( i % 3 ))
	
	if [ $div15 -eq 0 ]
		then
			echo "FizzBuzz"
	elif [ $div5 -eq 0 ]
		then
			echo "Buzz"
	elif [ $div3 -eq 0 ]
		then
			echo "Fizz"
	else
			echo "$i"
	fi
	i=$(( i + 1 ))
	
done