#!/usr/bin/env bash
# Prints Holberton School 10 times but hi on the 9th iteration

i=1

while [ $i -le 10 ]; do
	if [ $i -eq 9 ]
		then
			echo "Hi"
		else
			echo "Holberton School"
	fi
	i=$(( i + 1 ))
done
