#!/usr/bin/env bash
# Prints Holberton School 10 times
# print bad luck on 4th iteration
# print good lush on the 8th iteration

i=1

while [ $i -le 10 ]; do
	if [ $i -eq 4 ]
		then
			echo "bad luck"
	elif [ $i -eq 8 ]
		then
			echo "good luck"
	else
			echo "Holberton School"
	fi
	i=$(( i + 1 ))
done
