#!/usr/bin/env bash
# Prints numbers 1 to 20
# print bad luck from China on 4th iteration
# print bad luck from Japan on the 9th iteration
# print bad luck from Italy on the 17th iteration

i=1

while [ $i -le 20 ]; do
	
	case $i in
		4)
			echo "bad luck from China"
			;;
		
		9)
			echo "bad luck from Japan"
			;;
		
		17)
			echo "bad luck from Italy"
			;;

		*)
			echo "$i"
			;;
	esac

	i=$(( i + 1 ))
done
